server:
  port: 9000
spring:
  profiles:
    active: dev
  application:
    name: fluent-mybatis-demo
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.115.88.127:3306/clear_settle?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true&serverTimezone=GMT%2b8
      username: bill_user
      password: bill_user_password
      # ??druid???
      # ???????????????????????
      # ???????????
      initialSize: 10
      minIdle: 10
      maxActive: 200
      # ?????????????
      maxWait: 6000
      # ???????????????????????????????
      timeBetweenEvictionRunsMillis: 60000
      # ??????????????????????
      minEvictableIdleTimeMillis: 100000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # ??PSCache??????????PSCache???
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # ?????????filters????????sql?????'wall'?????
      filters: stat,wall,slf4j
      # ??connectProperties?????mergeSql????SQL??
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # ????DruidDataSource?????
      #useGlobalDataSourceStat: true
  jackson:
    timeZone: GMT+08:00
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
logging:
  level:
    com.ming.demo.fluent.mapper: debug
